# PARA DEFINIR LA RUTA DEL BANNER
spring: 
  banner: 
    location: classpath:/banner/bannerRutasSantaElena.txt
# PARA DEFINIR LA RUTA DE LOS HTML
  thymeleaf:
    prefix: classpath:/templates/
    #PARA CONFIGURAR EL PUERTO DONDE INCIARA LA APLICACION
server:  port: 8080